//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverflowTagServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StackOverflowTagServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb6
        ///vba
        ///vb
        ///homework
        ///grails
        ///coldfusion
        ///flash
        ///iphone
        ///air
        ///sifr
        ///ms-access
        ///db2
        ///vbscript
        ///perl
        ///sap
        ///jpa
        ///gql
        ///java-ee
        ///magento
        ///ipad
        ///qt
        ///weblogic
        ///blackberry
        ///gwt
        ///pentaho
        ///wordpress
        ///mac
        ///corba
        ///intellij-idea
        ///lucene
        ///safari
        ///seo
        ///redis
        ///itouch
        ///ant
        ///antlr
        ///ada
        ///gtk
        ///doctrine
        ///lotus
        ///tomcat
        ///jcl
        ///mongodb
        ///netlogo
        ///nosql
        ///smalltalk
        ///beamer
        ///spring
        ///symbian
        ///agile
        ///firebird
        ///samba
        ///jasper-reports
        ///sybase
        ///fortran
        ///qtp
        ///itunes
        ///sqlite
        ///soapui
        ///acrobat
        ///actionscript*
        ///flex*
        ///cocoa*
        ///struts*
        ///ruby*
        ///zen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leppie___excluded_tags {
            get {
                return ResourceManager.GetString("leppie___excluded_tags", resourceCulture);
            }
        }
    }
}
